name: Bug Report
description: Report a bug or issue with Beads Kanban
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and fix the issue.

  - type: checkboxes
    id: pre-checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I am using the latest version of Beads Kanban
          required: true
        - label: I have checked the [documentation](https://github.com/davidcforbes/Beads-Kanban#readme)
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I click the Columns button, nothing happens...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Open Kanban board
        2. Switch to Table view
        3. Click 'Columns' button
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A dropdown should appear with column visibility options
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Nothing happens when clicking the button
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: Any errors from VS Code Developer Console (Help > Toggle Developer Tools)
      placeholder: |
        TypeError: Cannot read property 'style' of null
          at board.js:1234
      render: shell

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: Found in Help > About
      placeholder: "1.85.0"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Beads Kanban Version
      description: Check Extensions panel
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: adapter
    attributes:
      label: Adapter Type
      description: Which adapter are you using?
      options:
        - sql.js (default, in-memory)
        - Daemon (bd CLI)
        - Not sure
    validations:
      required: true

  - type: input
    id: beads-version
    attributes:
      label: Beads CLI Version (if using daemon adapter)
      description: Run `bd --version`
      placeholder: "0.1.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This started happening after upgrading to version X...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to work on fixing this bug?
      options:
        - label: I would like to work on a fix for this issue
